### ISSUE TITLE
Add ability to go to different routes of github repo

### ISSUE THREAD

**Issue by aviskarkc10** [sindresorhus/gh-home#9]
I would like the ability to go to different pages of a GitHub repository. For example:

```
gh-home --pulls
```

Would be helpful if I could pass a param like this and it would take me to the pull requests of a repository. Similar for issues and other commonly visited pages.

Let me know if you would accept this. I will create a PR for this.

**Comment by sindresorhus** [comment]
Sure. I would prefer `--prs` and `--issues` for the flags though.
